### ISSUE TITLE
Is there more educational code in Rosetta Code

### ISSUE THREAD

**Issue by av930** [adsouza/Euclidean-Geometry#2]
I found you sample by searching for tens of minutes.
and I got notice at head of your intro: "The discovery of Rosetta Code made me abandon this."

do you find any example more helpful than this? about euclidean geometry?
if any, please let me know.

**Comment by adsouza** [comment]
What is the problem you are trying to solve?

**Comment by av930** [comment]
I am just finding a better example to under stand OOP concepts in java
specific

**Comment by adsouza** [comment]
Oh, in that case you can just use this project - the Java version is complete.

**Comment by av930** [comment]
ok. thanks. I appreciate it.

2018년 10월 2일 (화) 오후 6:41, adsouza <notifications@github.com>님이 작성:
